import { Spot, User } from './types';

export const INITIAL_SPOTS: Spot[] = [
  {
    id: 'spot-tokyo-01',
    user_id: 'spot-official-architect',
    user_name: 'Verified Architect',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1555529771-7888783a18d3?auto=format&fit=crop&w=1200&q=80',
    country: 'Japan',
    city: 'Tokyo',
    latitude: 35.6712,
    longitude: 139.7645,
    category: 'Store Interior',
    brand: 'Gentle Monster',
    description: 'Hyper-real kinetic sculpture installation integrated with brushed steel retail counters in Ginza.',
    captured_at: '2026-07-20T14:30:00Z',
    created_at: '2026-07-20T16:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-tokyo-01',
      colors: ['#18181B', '#C0C0C0', '#F97316', '#F5F5F0'],
      materials: ['Brushed Stainless Steel', 'Fluted Acrylic', 'Unfinished Concrete', 'Neon Quartz'],
      style: 'Cyberpunk Industrial',
      lighting: 'Dynamic Spot Accent & Linear Cove',
      composition: 'Monolithic Kinetic Focus',
      objects: ['Bionic Animatronic Head', 'Glass Pedestals', 'Monolithic Metal Pillars'],
      theme: 'Biomechanical Speculative Future',
    },
    ai_analysis: {
      spot_id: 'spot-tokyo-01',
      confidence: 0.96,
      is_verified: true,
      created_at: '2026-07-20T14:32:00Z',
      analysis: {
        category: 'Store Interior',
        brand: 'Gentle Monster',
        description: 'Kinetic art retail environment displaying high contrast metallic elements.',
        style: 'Cyberpunk Industrial',
        colors: ['#18181B', '#C0C0C0', '#F97316', '#F5F5F0'],
        materials: ['Brushed Stainless Steel', 'Fluted Acrylic', 'Unfinished Concrete'],
        lighting: 'Dynamic Spot Accent & Linear Cove',
        composition: 'Monolithic Kinetic Focus',
        objects: ['Animatronic Head', 'Glass Displays'],
        theme: 'Biomechanical Speculative Future',
      },
    },
  },
  {
    id: 'spot-paris-01',
    user_id: 'spot-official-architect',
    user_name: 'Jean-Luc Moreau',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1200&q=80',
    country: 'France',
    city: 'Paris',
    latitude: 48.8718,
    longitude: 2.3012,
    category: 'Window',
    brand: 'Louis Vuitton',
    description: 'Champs-Élysées summer window concept featuring multi-layered organic timber arcs with warm spotlighting.',
    captured_at: '2026-08-01T11:15:00Z',
    created_at: '2026-08-01T12:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-paris-01',
      colors: ['#1C1917', '#D4AF37', '#78350F', '#FEF08A'],
      materials: ['Steam-bent Walnut Wood', 'Polished Brass Rim', 'Low-iron Optical Glass', 'Silk Velvet'],
      style: 'Biophilic Luxury',
      lighting: 'Warm Concealed Ambient & Precise Spotlight',
      composition: 'Symmetrical Curved Depth',
      objects: ['Mannequins on Floating Wood Discs', 'Monogram Trunk Frame', 'Laser-cut Leaves'],
      theme: 'Organic Heritage Craftsmanship',
    },
    ai_analysis: {
      spot_id: 'spot-paris-01',
      confidence: 0.95,
      is_verified: true,
      created_at: '2026-08-01T11:17:00Z',
      analysis: {
        category: 'Window',
        brand: 'Louis Vuitton',
        description: 'Luxury window display with bent wood arc motifs and warm brass highlights.',
        style: 'Biophilic Luxury',
        colors: ['#1C1917', '#D4AF37', '#78350F', '#FEF08A'],
        materials: ['Steam-bent Walnut Wood', 'Polished Brass Rim'],
        lighting: 'Warm Concealed Ambient & Precise Spotlight',
        composition: 'Symmetrical Curved Depth',
        objects: ['Mannequins', 'Trunk Displays'],
        theme: 'Organic Heritage Craftsmanship',
      },
    },
  },
  {
    id: 'spot-ny-01',
    user_id: 'spot-official-architect',
    user_name: 'Marcus Vance',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80',
    country: 'United States',
    city: 'New York',
    latitude: 40.7224,
    longitude: -73.9978,
    category: 'Store Interior',
    brand: 'Glossier',
    description: 'SoHo flagship interior featuring soft millennial pink plaster walls, oversized foam pedestals, and chrome detailing.',
    captured_at: '2026-07-28T13:10:00Z',
    created_at: '2026-07-28T14:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-ny-01',
      colors: ['#FDE8E8', '#9F1239', '#FDA4AF', '#E5E7EB'],
      materials: ['Venetian Soft Plaster', 'Mirror-polished Chrome', 'Cast Resin', 'Terrazzo Flooring'],
      style: 'Soft Sculptural Surrealism',
      lighting: 'Diffused Ceiling Lightbox & Vanity Ring Lights',
      composition: 'Curvilinear Fluid Flow',
      objects: ['Monolithic Tester Tables', 'Integrated Sink Basins', 'Custom Neon Mirrors'],
      theme: 'Playful Tactile Beauty Playground',
    },
    ai_analysis: {
      spot_id: 'spot-ny-01',
      confidence: 0.94,
      is_verified: true,
      created_at: '2026-07-28T13:12:00Z',
      analysis: {
        category: 'Store Interior',
        brand: 'Glossier',
        description: 'Monochromatic pink interior store layout with chrome fixtures in SoHo.',
        style: 'Soft Sculptural Surrealism',
        colors: ['#FDE8E8', '#9F1239', '#FDA4AF', '#E5E7EB'],
        materials: ['Venetian Soft Plaster', 'Mirror-polished Chrome'],
        lighting: 'Diffused Ceiling Lightbox & Vanity Ring Lights',
        composition: 'Curvilinear Fluid Flow',
        objects: ['Tester Tables', 'Neon Mirrors'],
        theme: 'Playful Tactile Beauty Playground',
      },
    },
  },
  {
    id: 'spot-london-01',
    user_id: 'spot-official-architect',
    user_name: 'Oliver Wright',
    user_avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1537832816519-689ad163238b?auto=format&fit=crop&w=1200&q=80',
    country: 'United Kingdom',
    city: 'London',
    latitude: 51.5118,
    longitude: -0.1388,
    category: 'Store Exterior',
    brand: 'Burberry',
    description: 'Bond Street flagship façade completely wrapped in dynamic mirrored check tiles that reflect heritage London brickwork.',
    captured_at: '2026-07-15T10:00:00Z',
    created_at: '2026-07-15T11:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-london-01',
      colors: ['#D97706', '#FEF3C7', '#451A03', '#1F2937'],
      materials: ['Specular Anodized Aluminum', 'Tempered Reflected Glass', 'Portland Stone Trim'],
      style: 'Neo-Heritage Expressionism',
      lighting: 'Integrated Kinetic LED Pixel Facade',
      composition: 'Grid Pattern Disruption',
      objects: ['Mirrored Check Panels', 'Illuminated Monogram Crest'],
      theme: 'Reflective Tradition in Digital Motion',
    },
    ai_analysis: {
      spot_id: 'spot-london-01',
      confidence: 0.97,
      is_verified: true,
      created_at: '2026-07-15T10:02:00Z',
      analysis: {
        category: 'Store Exterior',
        brand: 'Burberry',
        description: 'Mirrored modular tile storefront design on Bond Street.',
        style: 'Neo-Heritage Expressionism',
        colors: ['#D97706', '#FEF3C7', '#451A03', '#1F2937'],
        materials: ['Specular Anodized Aluminum', 'Tempered Reflected Glass'],
        lighting: 'Integrated Kinetic LED Pixel Facade',
        composition: 'Grid Pattern Disruption',
        objects: ['Mirrored Panels'],
        theme: 'Reflective Tradition in Digital Motion',
      },
    },
  },
  {
    id: 'spot-milan-01',
    user_id: 'spot-official-architect',
    user_name: 'Sofia Rossi',
    user_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
    country: 'Italy',
    city: 'Milan',
    latitude: 45.4682,
    longitude: 9.1944,
    category: 'Exhibition',
    brand: 'Bottega Veneta',
    description: 'Salone del Mobile immersive lounge pavilion constructed with woven leather acoustic panels and volcanic stone seats.',
    captured_at: '2026-06-10T15:20:00Z',
    created_at: '2026-06-10T16:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-milan-01',
      colors: ['#15803D', '#F5F5F4', '#B45309', '#292524'],
      materials: ['Intrecciato Nappa Leather', 'Basalt Volcanic Stone', 'Brushed Warm Bronze', 'Raw Linen'],
      style: 'Craft Rationalism',
      lighting: 'Low-key Warm Accent & Spot Highlights',
      composition: 'Concentric Pavilion Enclosure',
      objects: ['Low Basalt Benches', 'Woven Acoustic Screen Panels', 'Sunken Seating Pit'],
      theme: 'Tactile Sanctuary & Modern Craft',
    },
    ai_analysis: {
      spot_id: 'spot-milan-01',
      confidence: 0.95,
      is_verified: true,
      created_at: '2026-06-10T15:22:00Z',
      analysis: {
        category: 'Exhibition',
        brand: 'Bottega Veneta',
        description: 'Exhibition space showcasing woven leather walls and volcanic stone seating in Milan.',
        style: 'Craft Rationalism',
        colors: ['#15803D', '#F5F5F4', '#B45309', '#292524'],
        materials: ['Intrecciato Nappa Leather', 'Basalt Volcanic Stone'],
        lighting: 'Low-key Warm Accent & Spot Highlights',
        composition: 'Concentric Pavilion Enclosure',
        objects: ['Basalt Benches', 'Acoustic Panels'],
        theme: 'Tactile Sanctuary & Modern Craft',
      },
    },
  },
  {
    id: 'spot-tokyo-02',
    user_id: 'spot-official-architect',
    user_name: 'Verified Architect',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
    country: 'Japan',
    city: 'Tokyo',
    latitude: 35.6664,
    longitude: 139.7092,
    category: 'Window',
    brand: 'Dior',
    description: 'Omotesando storefront window utilizing traditional Japanese Washi paper lanterns with modern geometric brass wireframes.',
    captured_at: '2026-07-22T19:00:00Z',
    created_at: '2026-07-22T20:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-tokyo-02',
      colors: ['#FFFDF5', '#D4AF37', '#222222', '#E8D8C8'],
      materials: ['Handmade Washi Paper', 'Fine Brass Rods', 'Ultra-clear Glass', 'Black Ash Wood'],
      style: 'Minimalist Oriental Modernism',
      lighting: 'Internal Paper Lantern Glow & Exterior Narrow Spot',
      composition: 'Floating Geometric Balance',
      objects: ['Floating Washi Spheres', 'Polished Brass Lattice', 'Pedestal Display Cases'],
      theme: 'Illuminated Craft Translucency',
    },
    ai_analysis: {
      spot_id: 'spot-tokyo-02',
      confidence: 0.93,
      is_verified: true,
      created_at: '2026-07-22T19:03:00Z',
      analysis: {
        category: 'Window',
        brand: 'Dior',
        description: 'Window display with lit Washi paper lanterns and brass frames.',
        style: 'Minimalist Oriental Modernism',
        colors: ['#FFFDF5', '#D4AF37', '#222222', '#E8D8C8'],
        materials: ['Handmade Washi Paper', 'Fine Brass Rods'],
        lighting: 'Internal Paper Lantern Glow & Exterior Narrow Spot',
        composition: 'Floating Geometric Balance',
        objects: ['Washi Spheres', 'Brass Lattice'],
        theme: 'Illuminated Craft Translucency',
      },
    },
  },
  {
    id: 'spot-paris-02',
    user_id: 'spot-official-architect',
    user_name: 'Jean-Luc Moreau',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=1200&q=80',
    country: 'France',
    city: 'Paris',
    latitude: 48.8553,
    longitude: 2.3642,
    category: 'Pop-up Store',
    brand: 'Jacquemus',
    description: 'Le Marais pop-up concept featuring monochromatic butter yellow foam structures and curved retail racks.',
    captured_at: '2026-07-30T15:00:00Z',
    created_at: '2026-07-30T16:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-paris-02',
      colors: ['#FEF08A', '#EAB308', '#713F12', '#FFFFFF'],
      materials: ['High-density Molded Foam', 'Matte Lacquered Steel', 'Frosted Yellow Glass'],
      style: 'Surrealist Pop Minimalism',
      lighting: 'High-luminance Soft Overhead Diffusion',
      composition: 'Monochromatic Sculptural Blocks',
      objects: ['Butter Yellow Oversized Chairs', 'Curved Display Walls', 'Giant Product Props'],
      theme: 'Sun-drenched Playful Surrealism',
    },
    ai_analysis: {
      spot_id: 'spot-paris-02',
      confidence: 0.92,
      is_verified: true,
      created_at: '2026-07-30T15:02:00Z',
      analysis: {
        category: 'Pop-up Store',
        brand: 'Jacquemus',
        description: 'Monochromatic yellow pop-up retail space with foam furniture.',
        style: 'Surrealist Pop Minimalism',
        colors: ['#FEF08A', '#EAB308', '#713F12', '#FFFFFF'],
        materials: ['High-density Molded Foam', 'Matte Lacquered Steel'],
        lighting: 'High-luminance Soft Overhead Diffusion',
        composition: 'Monochromatic Sculptural Blocks',
        objects: ['Yellow Chairs', 'Display Walls'],
        theme: 'Sun-drenched Playful Surrealism',
      },
    },
  },
  {
    id: 'spot-ny-02',
    user_id: 'spot-official-architect',
    user_name: 'Marcus Vance',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    country: 'United States',
    city: 'New York',
    latitude: 40.7626,
    longitude: -73.9738,
    category: 'Store Exterior',
    brand: 'Tiffany & Co.',
    description: 'Fifth Avenue landmark façade featuring multi-faceted glass curtain wall with custom robin-egg blue lighting at dusk.',
    captured_at: '2026-07-29T20:15:00Z',
    created_at: '2026-07-29T21:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-ny-02',
      colors: ['#06B6D4', '#E0F2FE', '#0284C7', '#FFFFFF'],
      materials: ['Custom Faceted Glass Tiles', 'Polished Platinum Rim', 'White Indiana Limestone'],
      style: 'Monumental Art Deco Modernism',
      lighting: 'Custom RGBW Architectural Glow',
      composition: 'Vertical Tower Symmetry',
      objects: ['Atlas Clock Statue', 'Faceted Glass Facade Modules'],
      theme: 'Illuminated Iconic Luxury Heritage',
    },
    ai_analysis: {
      spot_id: 'spot-ny-02',
      confidence: 0.98,
      is_verified: true,
      created_at: '2026-07-29T20:17:00Z',
      analysis: {
        category: 'Store Exterior',
        brand: 'Tiffany & Co.',
        description: 'Illuminated glass building façade on Fifth Avenue.',
        style: 'Monumental Art Deco Modernism',
        colors: ['#06B6D4', '#E0F2FE', '#0284C7', '#FFFFFF'],
        materials: ['Custom Faceted Glass Tiles', 'Polished Platinum Rim'],
        lighting: 'Custom RGBW Architectural Glow',
        composition: 'Vertical Tower Symmetry',
        objects: ['Atlas Clock', 'Faceted Glass Modules'],
        theme: 'Illuminated Iconic Luxury Heritage',
      },
    },
  },
  {
    id: 'spot-tokyo-03',
    user_id: 'spot-official-architect',
    user_name: 'Verified Architect',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1578932750294-f5075e85f44a?auto=format&fit=crop&w=1200&q=80',
    country: 'Japan',
    city: 'Tokyo',
    latitude: 35.6723,
    longitude: 139.7634,
    category: 'Window',
    brand: 'Hermès',
    description: 'Ginza Maison Hermès paper origami installation window with golden sunlight projections.',
    captured_at: '2026-08-08T16:00:00Z',
    created_at: '2026-08-08T17:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-tokyo-03',
      colors: ['#D97706', '#FEF3C7', '#78350F', '#1F2937'],
      materials: ['Handmade Washi Paper', 'Polished Brass Rim', 'Low-iron Optical Glass'],
      style: 'Minimalist Oriental Modernism',
      lighting: 'Warm Ambient Cove & Indirect Floor Spotlights',
      composition: 'Floating Geometric Balance',
      objects: ['Origami Sculptures', 'Sunlight Projection Frame'],
      theme: 'Sun-drenched Craft Precision',
    },
    ai_analysis: {
      spot_id: 'spot-tokyo-03',
      confidence: 0.97,
      is_verified: true,
      created_at: '2026-08-08T16:05:00Z',
      analysis: {
        category: 'Window',
        brand: 'Hermès',
        description: 'Golden paper origami installation in Ginza window display.',
        style: 'Minimalist Oriental Modernism',
        colors: ['#D97706', '#FEF3C7', '#78350F', '#1F2937'],
        materials: ['Handmade Washi Paper', 'Polished Brass Rim'],
        lighting: 'Warm Ambient Cove & Indirect Floor Spotlights',
        composition: 'Floating Geometric Balance',
        objects: ['Origami Sculptures'],
        theme: 'Sun-drenched Craft Precision',
      },
    },
  },
  {
    id: 'spot-paris-03',
    user_id: 'spot-official-architect',
    user_name: 'Jean-Luc Moreau',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80',
    country: 'France',
    city: 'Paris',
    latitude: 48.8672,
    longitude: 2.3294,
    category: 'Store Exterior',
    brand: 'Chanel',
    description: 'Monolithic noir octagonal storefront framing the historic Place Vendôme column reflection.',
    captured_at: '2026-08-07T11:00:00Z',
    created_at: '2026-08-07T12:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-paris-03',
      colors: ['#2EC4B6', '#00A896', '#18181B', '#E5E5E5'],
      materials: ['Blackized Steel Frames', 'Mirror-polished Chrome', 'White Indiana Limestone'],
      style: 'Neo-Heritage Expressionism',
      lighting: 'Dynamic Spot Accent & Linear Cove',
      composition: 'Vertical Tower Symmetry',
      objects: ['Octagonal Glass Arches', 'Monogram Plaque'],
      theme: 'Timeless Monolithic Elegance',
    },
    ai_analysis: {
      spot_id: 'spot-paris-03',
      confidence: 0.99,
      is_verified: true,
      created_at: '2026-08-07T11:03:00Z',
      analysis: {
        category: 'Store Exterior',
        brand: 'Chanel',
        description: 'Blackized steel octagonal storefront on Place Vendôme.',
        style: 'Neo-Heritage Expressionism',
        colors: ['#2EC4B6', '#00A896', '#18181B', '#E5E5E5'],
        materials: ['Blackized Steel Frames', 'White Indiana Limestone'],
        lighting: 'Dynamic Spot Accent & Linear Cove',
        composition: 'Vertical Tower Symmetry',
        objects: ['Octagonal Arches'],
        theme: 'Timeless Monolithic Elegance',
      },
    },
  },
  {
    id: 'spot-ny-03',
    user_id: 'spot-official-architect',
    user_name: 'Marcus Vance',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    country: 'United States',
    city: 'New York',
    latitude: 40.7242,
    longitude: -73.9984,
    category: 'Store Interior',
    brand: 'Prada',
    description: 'SoHo wave wooden staircase integrated with transparent glass display pods and green marble.',
    captured_at: '2026-08-04T14:20:00Z',
    created_at: '2026-08-04T15:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-ny-03',
      colors: ['#15803D', '#D97706', '#18181B', '#F5F5F4'],
      materials: ['Intrecciato Nappa Leather', 'Natural Travertine Stone', 'Mirror-polished Chrome'],
      style: 'Craft Rationalism',
      lighting: 'Diffused Ceiling Lightbox & Vanity Ring Lights',
      composition: 'Curvilinear Fluid Flow',
      objects: ['Curved Wave Staircase', 'Glass Display Pods'],
      theme: 'Architectural Wave Motion',
    },
    ai_analysis: {
      spot_id: 'spot-ny-03',
      confidence: 0.96,
      is_verified: true,
      created_at: '2026-08-04T14:22:00Z',
      analysis: {
        category: 'Store Interior',
        brand: 'Prada',
        description: 'Iconic wave staircase in SoHo with green marble highlights.',
        style: 'Craft Rationalism',
        colors: ['#15803D', '#D97706', '#18181B', '#F5F5F4'],
        materials: ['Natural Travertine Stone', 'Mirror-polished Chrome'],
        lighting: 'Diffused Ceiling Lightbox & Vanity Ring Lights',
        composition: 'Curvilinear Fluid Flow',
        objects: ['Wave Staircase'],
        theme: 'Architectural Wave Motion',
      },
    },
  },
  {
    id: 'spot-london-02',
    user_id: 'spot-official-architect',
    user_name: 'Oliver Wright',
    user_avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    country: 'United Kingdom',
    city: 'London',
    latitude: 51.5142,
    longitude: -0.1415,
    category: 'Store Interior',
    brand: 'Apple',
    description: 'Soaring grand archways lined with living Ficus trees and custom monolithic terrazzo tables.',
    captured_at: '2026-08-02T13:00:00Z',
    created_at: '2026-08-02T14:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-london-02',
      colors: ['#E4E4E7', '#15803D', '#71717A', '#FFFFFF'],
      materials: ['Portland Stone Trim', 'Suspended Moss', 'Terrazzo Flooring'],
      style: 'Biophilic Luxury',
      lighting: 'High-luminance Soft Overhead Diffusion',
      composition: 'Symmetrical Curved Depth',
      objects: ['Living Ficus Trees', 'Monolithic Terrazzo Benches'],
      theme: 'Biophilic Heritage Sanctuary',
    },
    ai_analysis: {
      spot_id: 'spot-london-02',
      confidence: 0.98,
      is_verified: true,
      created_at: '2026-08-02T13:02:00Z',
      analysis: {
        category: 'Store Interior',
        brand: 'Apple',
        description: 'Biophilic retail atrium lined with trees and stone arches.',
        style: 'Biophilic Luxury',
        colors: ['#E4E4E7', '#15803D', '#71717A', '#FFFFFF'],
        materials: ['Portland Stone Trim', 'Terrazzo Flooring'],
        lighting: 'High-luminance Soft Overhead Diffusion',
        composition: 'Symmetrical Curved Depth',
        objects: ['Living Trees'],
        theme: 'Biophilic Heritage Sanctuary',
      },
    },
  },
  {
    id: 'spot-milan-02',
    user_id: 'spot-official-architect',
    user_name: 'Sofia Rossi',
    user_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80',
    country: 'Italy',
    city: 'Milan',
    latitude: 45.4657,
    longitude: 9.1902,
    category: 'Window',
    brand: 'Gucci',
    description: 'Opulent velvet padded window nook with vintage brass luggage mounts in the Milan Galleria.',
    captured_at: '2026-07-31T18:40:00Z',
    created_at: '2026-07-31T19:30:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-milan-02',
      colors: ['#9F1239', '#D4AF37', '#1C1917', '#FEF08A'],
      materials: ['Silk Velvet', 'Polished Brass Rim', 'Black Ash Wood'],
      style: 'Monumental Art Deco Modernism',
      lighting: 'Warm Concealed Ambient & Precise Spotlight',
      composition: 'Monochromatic Sculptural Blocks',
      objects: ['Vintage Brass Luggage', 'Velvet Nook'],
      theme: 'Opulent Maximalist Heritage',
    },
    ai_analysis: {
      spot_id: 'spot-milan-02',
      confidence: 0.95,
      is_verified: true,
      created_at: '2026-07-31T18:42:00Z',
      analysis: {
        category: 'Window',
        brand: 'Gucci',
        description: 'Velvet window display with brass luggage fixtures in Milan.',
        style: 'Monumental Art Deco Modernism',
        colors: ['#9F1239', '#D4AF37', '#1C1917', '#FEF08A'],
        materials: ['Silk Velvet', 'Polished Brass Rim'],
        lighting: 'Warm Concealed Ambient & Precise Spotlight',
        composition: 'Monochromatic Sculptural Blocks',
        objects: ['Brass Luggage'],
        theme: 'Opulent Maximalist Heritage',
      },
    },
  },
  {
    id: 'spot-tokyo-04',
    user_id: 'spot-official-architect',
    user_name: 'Verified Architect',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80',
    country: 'Japan',
    city: 'Tokyo',
    latitude: 35.6601,
    longitude: 139.7006,
    category: 'Pop-up Store',
    brand: 'Balenciaga',
    description: 'Raw construction scaffolding environment wrapped in heavy industrial plastic curtains.',
    captured_at: '2026-07-27T21:10:00Z',
    created_at: '2026-07-27T22:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-tokyo-04',
      colors: ['#18181B', '#71717A', '#F97316', '#E4E4E7'],
      materials: ['Unfinished Concrete', 'Fluted Acrylic', 'Blackized Steel Frames'],
      style: 'Cyberpunk Industrial',
      lighting: 'Linear LED Outline & Soft Floor Wash',
      composition: 'Grid Pattern Disruption',
      objects: ['Steel Scaffolding', 'Tarpaulin Curtains'],
      theme: 'Raw Anti-Design Deconstruction',
    },
    ai_analysis: {
      spot_id: 'spot-tokyo-04',
      confidence: 0.94,
      is_verified: true,
      created_at: '2026-07-27T21:12:00Z',
      analysis: {
        category: 'Pop-up Store',
        brand: 'Balenciaga',
        description: 'Raw scaffolding pop-up store environment in Shibuya.',
        style: 'Cyberpunk Industrial',
        colors: ['#18181B', '#71717A', '#F97316', '#E4E4E7'],
        materials: ['Unfinished Concrete', 'Blackized Steel Frames'],
        lighting: 'Linear LED Outline & Soft Floor Wash',
        composition: 'Grid Pattern Disruption',
        objects: ['Scaffolding Pipes'],
        theme: 'Raw Anti-Design Deconstruction',
      },
    },
  },
  {
    id: 'spot-paris-04',
    user_id: 'spot-official-architect',
    user_name: 'Jean-Luc Moreau',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=1200&q=80',
    country: 'France',
    city: 'Paris',
    latitude: 48.8682,
    longitude: 2.3068,
    category: 'Store Interior',
    brand: 'Celine',
    description: 'Sculptural Grand Antique marble podiums set against mirrored brass panels and muted plaster.',
    captured_at: '2026-07-25T14:50:00Z',
    created_at: '2026-07-25T15:30:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-paris-04',
      colors: ['#1C1917', '#E4E4E7', '#B45309', '#27272A'],
      materials: ['Natural Travertine Stone', 'Polished Brass Rim', 'Venetian Soft Plaster'],
      style: 'Soft Sculptural Surrealism',
      lighting: 'Low-key Warm Accent & Spot Highlights',
      composition: 'Monolithic Kinetic Focus',
      objects: ['Grand Antique Marble Podiums', 'Brass Mirror Wall'],
      theme: 'Monolithic French Neo-Classical Minimal',
    },
    ai_analysis: {
      spot_id: 'spot-paris-04',
      confidence: 0.97,
      is_verified: true,
      created_at: '2026-07-25T14:52:00Z',
      analysis: {
        category: 'Store Interior',
        brand: 'Celine',
        description: 'Sculptural marble podiums with brass mirror panels.',
        style: 'Soft Sculptural Surrealism',
        colors: ['#1C1917', '#E4E4E7', '#B45309', '#27272A'],
        materials: ['Natural Travertine Stone', 'Polished Brass Rim'],
        lighting: 'Low-key Warm Accent & Spot Highlights',
        composition: 'Monolithic Kinetic Focus',
        objects: ['Marble Podiums'],
        theme: 'Monolithic French Neo-Classical Minimal',
      },
    },
  },
  {
    id: 'spot-ny-04',
    user_id: 'spot-official-architect',
    user_name: 'Marcus Vance',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1200&q=80',
    country: 'United States',
    city: 'New York',
    latitude: 40.7108,
    longitude: -73.9635,
    category: 'Store Interior',
    brand: 'Kith',
    description: 'Custom footwear archway constructed from 500 cast white sneaker molds with marble countertops.',
    captured_at: '2026-07-18T12:40:00Z',
    created_at: '2026-07-18T13:30:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-ny-04',
      colors: ['#F5F5EC', '#18181B', '#C0C0C0', '#D97706'],
      materials: ['Terrazzo Flooring', 'Brushed Stainless Steel', 'Natural Travertine Stone'],
      style: 'Minimalist Brutalism',
      lighting: 'Diffused Ceiling Lightbox & Vanity Ring Lights',
      composition: 'Symmetrical Curved Depth',
      objects: ['Sneaker Mold Archway', 'Marble Countertop'],
      theme: 'Sculptural Sneaker Culture Heritage',
    },
    ai_analysis: {
      spot_id: 'spot-ny-04',
      confidence: 0.97,
      is_verified: true,
      created_at: '2026-07-18T12:42:00Z',
      analysis: {
        category: 'Store Interior',
        brand: 'Kith',
        description: 'Sneaker mold archway retail layout in Williamsburg.',
        style: 'Minimalist Brutalism',
        colors: ['#F5F5EC', '#18181B', '#C0C0C0', '#D97706'],
        materials: ['Terrazzo Flooring', 'Brushed Stainless Steel'],
        lighting: 'Diffused Ceiling Lightbox & Vanity Ring Lights',
        composition: 'Symmetrical Curved Depth',
        objects: ['Sneaker Archway'],
        theme: 'Sculptural Sneaker Culture Heritage',
      },
    },
  },
  {
    id: 'spot-paris-05',
    user_id: 'spot-official-architect',
    user_name: 'Jean-Luc Moreau',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&w=1200&q=80',
    country: 'France',
    city: 'Paris',
    latitude: 48.8654,
    longitude: 2.3288,
    category: 'Store Interior',
    brand: 'Saint Laurent',
    description: 'Minimalist noir marble showroom with mirror polished steel racks on Rue Saint-Honoré.',
    captured_at: '2026-08-09T14:00:00Z',
    created_at: '2026-08-09T15:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-paris-05',
      colors: ['#18181B', '#C0C0C0', '#E4E4E7', '#000000'],
      materials: ['Hairline Stainless Steel', 'Natural Travertine Stone', 'Mirror-polished Chrome'],
      style: 'Cyberpunk Industrial',
      lighting: 'Linear LED Outline & Soft Floor Wash',
      composition: 'Monolithic Kinetic Focus',
      objects: ['Noir Marble Podiums', 'Chrome Hangers'],
      theme: 'High Contrast French Rock Minimal',
    },
    ai_analysis: {
      spot_id: 'spot-paris-05',
      confidence: 0.98,
      is_verified: true,
      created_at: '2026-08-09T14:02:00Z',
      analysis: {
        category: 'Store Interior',
        brand: 'Saint Laurent',
        description: 'Black marble and mirror chrome showroom on Rue Saint-Honoré.',
        style: 'Cyberpunk Industrial',
        colors: ['#18181B', '#C0C0C0', '#E4E4E7', '#000000'],
        materials: ['Hairline Stainless Steel', 'Mirror-polished Chrome'],
        lighting: 'Linear LED Outline & Soft Floor Wash',
        composition: 'Monolithic Kinetic Focus',
        objects: ['Marble Podiums'],
        theme: 'High Contrast French Rock Minimal',
      },
    },
  },
  {
    id: 'spot-tokyo-05',
    user_id: 'spot-official-architect',
    user_name: 'Verified Architect',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    country: 'Japan',
    city: 'Tokyo',
    latitude: 35.6658,
    longitude: 139.7118,
    category: 'Store Interior',
    brand: 'Loewe',
    description: 'Jonathan Anderson curated Casa Loewe interior featuring ceramic art, oak shelves, and custom hand-woven rugs.',
    captured_at: '2026-08-08T18:00:00Z',
    created_at: '2026-08-08T19:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-tokyo-05',
      colors: ['#78350F', '#B45309', '#F5F5F0', '#1C1917'],
      materials: ['Steam-bent Walnut Wood', 'Raw Linen', 'Natural Travertine Stone'],
      style: 'Craft Rationalism',
      lighting: 'Warm Concealed Ambient & Precise Spotlight',
      composition: 'Asymmetrical Serene Voids',
      objects: ['Ceramic Art Objects', 'Hand-woven Rugs'],
      theme: 'Artistic Craft Sanctuary',
    },
    ai_analysis: {
      spot_id: 'spot-tokyo-05',
      confidence: 0.97,
      is_verified: true,
      created_at: '2026-08-08T18:02:00Z',
      analysis: {
        category: 'Store Interior',
        brand: 'Loewe',
        description: 'Casa Loewe Omotesando interior with ceramic sculptures.',
        style: 'Craft Rationalism',
        colors: ['#78350F', '#B45309', '#F5F5F0', '#1C1917'],
        materials: ['Steam-bent Walnut Wood', 'Raw Linen'],
        lighting: 'Warm Concealed Ambient & Precise Spotlight',
        composition: 'Asymmetrical Serene Voids',
        objects: ['Ceramic Sculptures'],
        theme: 'Artistic Craft Sanctuary',
      },
    },
  },
  {
    id: 'spot-ny-05',
    user_id: 'spot-official-architect',
    user_name: 'Marcus Vance',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    country: 'United States',
    city: 'New York',
    latitude: 40.7592,
    longitude: -73.9760,
    category: 'Store Exterior',
    brand: 'Cartier',
    description: 'Fifth Avenue neo-renaissance mansion storefront with gold panther sculpture accents.',
    captured_at: '2026-08-06T19:00:00Z',
    created_at: '2026-08-06T20:00:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-ny-05',
      colors: ['#D4AF37', '#18181B', '#FFFFFF', '#78350F'],
      materials: ['Polished Brass Rim', 'White Indiana Limestone', 'Low-iron Optical Glass'],
      style: 'Monumental Art Deco Modernism',
      lighting: 'Warm Concealed Ambient & Precise Spotlight',
      composition: 'Vertical Tower Symmetry',
      objects: ['Gold Panther Statue', 'Mansion Portico'],
      theme: 'Illuminated Heritage Glamour',
    },
    ai_analysis: {
      spot_id: 'spot-ny-05',
      confidence: 0.99,
      is_verified: true,
      created_at: '2026-08-06T19:02:00Z',
      analysis: {
        category: 'Store Exterior',
        brand: 'Cartier',
        description: 'Cartier Fifth Avenue mansion facade with panther sculpture.',
        style: 'Monumental Art Deco Modernism',
        colors: ['#D4AF37', '#18181B', '#FFFFFF', '#78350F'],
        materials: ['Polished Brass Rim', 'White Indiana Limestone'],
        lighting: 'Warm Concealed Ambient & Precise Spotlight',
        composition: 'Vertical Tower Symmetry',
        objects: ['Panther Statue'],
        theme: 'Illuminated Heritage Glamour',
      },
    },
  },
  {
    id: 'spot-milan-03',
    user_id: 'spot-official-architect',
    user_name: 'Sofia Rossi',
    user_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    image_url: 'https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?auto=format&fit=crop&w=1200&q=80',
    country: 'Italy',
    city: 'Milan',
    latitude: 45.4690,
    longitude: 9.1962,
    category: 'Window',
    brand: 'Miu Miu',
    description: 'Pastel yellow damask silk window nook with brass framing in the Milan fashion quadrant.',
    captured_at: '2026-08-05T17:30:00Z',
    created_at: '2026-08-05T18:30:00Z',
    is_verified: true,
    attributes: {
      spot_id: 'spot-milan-03',
      colors: ['#FEF08A', '#D4AF37', '#18181B', '#F5F5F0'],
      materials: ['Silk Velvet', 'Polished Brass Rim', 'Low-iron Optical Glass'],
      style: 'Surrealist Pop Minimalism',
      lighting: 'Warm Concealed Ambient & Precise Spotlight',
      composition: 'Monochromatic Sculptural Blocks',
      objects: ['Silk Damask Backdrop', 'Brass Handbag Holders'],
      theme: 'Playful Feminine Opulence',
    },
    ai_analysis: {
      spot_id: 'spot-milan-03',
      confidence: 0.96,
      is_verified: true,
      created_at: '2026-08-05T17:32:00Z',
      analysis: {
        category: 'Window',
        brand: 'Miu Miu',
        description: 'Silk damask window display in Milan fashion quadrant.',
        style: 'Surrealist Pop Minimalism',
        colors: ['#FEF08A', '#D4AF37', '#18181B', '#F5F5F0'],
        materials: ['Silk Velvet', 'Polished Brass Rim'],
        lighting: 'Warm Concealed Ambient & Precise Spotlight',
        composition: 'Monochromatic Sculptural Blocks',
        objects: ['Handbag Displays'],
        theme: 'Playful Feminine Opulence',
      },
    },
  },
];

